server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:mykeystore.jks
    key-store-password: mypassword
    key-alias: mykey

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liSJT9fMJUDPIdtc
            client-secret: 91bcaa8932bc7801016879455bc94f81a56e60c2
            scope: read:user, user:email
            redirect-uri: "https://localhost:8443/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.sql: DEBUG
    org.springframework.boot: DEBUG